version: '3.8'
name: 'chat-bot'
services:
  db:
    image: postgres:14.1-alpine
    container_name: db
    platform: linux/x86_64
    ports:
      - ${DB_PORT}:${DB_PORT}
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    volumes:
      - db-data:/var/lib/postgresql/data
    restart: 'always'

    cap_add:
    - SYS_NICE

volumes:
  db-data:
